### ISSUE TITLE
RSS Feed Please

### ISSUE THREAD

**Issue by heywoodlh** [salineselin/salinesel.in#1]
Can you put an RSS feed on your site (or make it more obvious if there already is one setup) so that those of us who want to keep up with your content can? 

Thanks! :)

**Comment by cnorling** [comment]
Sure :)

**Comment by cnorling** [comment]
I added a link underneath my profile picture with an RSS icon, does that work for you?
![image](https://user-images.githubusercontent.com/47022783/178837652-5f59eecb-a35e-40f0-894b-718d0f29e1c9.png)

**Comment by heywoodlh** [comment]
Perfect, thanks!
